forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/stdlib', '4.1.0'

mod 'puppetlabs/apache', '1.1.1'
  :git => "git://github.com/puppetlabs/puppetlabs-apache.git"

mod 'puppetlabs/apt', '1.1.1'
  :git => "git://github.com/puppetlabs/puppetlabs-apt.git"
  :ref => 'any/valid/gitref'
